### PR TITLE
Travis and npm updates

### PR DESCRIPTION
**Pull request by tgabi333**
uglify-js updated to avoid security vulerabilites:
https://nodesecurity.io/advisories/uglify-js_regular-expression-denial-of-service
https://nodesecurity.io/advisories/uglify-js_incorrect-handling-of-non-boolean-comparisons-during-minification

travis updated to support node 0.12, 4 and 5

### CODE REVIEW

**Comment by tgabi333** [comment]
Could you please turn on travis builds for pull requests?

**Comment by rreusser** [comment]
No problem! I've turned them on. You can see them here: https://travis-ci.org/scijs/cwise/pull_requests

I think another push should trigger it.

**Comment by rreusser** [comment]
Looks good to me. Thanks for the maintenance update.

**Comment by rreusser** [comment]
1.0.9 published to npm. When I get a chance, I'll trickle this down through the dependents.

**Comment by tgabi333** [comment]
@rreusser Thank you!

**Pull request merged**
